export const GET_TAGS_REQUEST = 'GET_TAGS_REQUEST';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';

export const GET_TAGS_BY_USERID_REQUEST = 'GET_TAGS_BY_USERID_REQUEST';
export const GET_TAGS_BY_USERID_SUCCESS = 'GET_TAGS_BY_USERID_SUCCESS';

export const CREATE_TAG_REQUEST = 'CREATE_TAG_REQUEST';
export const CREATE_TAG_SUCCESS = 'CREATE_TAG_SUCCESS';

export const UPDATE_TAG_REQUEST = 'UPDATE_TAG_REQUEST';
export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS';

export const DELETE_TAG_REQUEST = 'DELETE_TAG_REQUEST';
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';

export const ADD_TAG_TO_NOTE_REQUEST = 'ADD_TAG_TO_NOTE_REQUEST';
export const ADD_TAG_TO_NOTE_SUCCESS = 'ADD_TAG_TO_NOTE_SUCCESS';

export const REMOVE_TAG_FROM_NOTE_REQUEST = 'REMOVE_TAG_FROM_NOTE_REQUEST';
export const REMOVE_TAG_FROM_NOTE_SUCCESS = 'REMOVE_TAG_FROM_NOTE_SUCCESS';

export const GET_TAGS_BY_NOTEID_REQUEST = 'GET_TAGS_BY_NOTEID_REQUEST';
export const GET_TAGS_BY_NOTEID_SUCCESS = 'GET_TAGS_BY_NOTEID_SUCCESS';

export const CLEAR_TAGS_ERROR = 'CLEAR_TAGS_ERROR';